project:
  type: website
  output-dir: docs
  resources:
    - "lecture-scripts/*"
    - "assignments"
    - "lecture-notes/*.ipynb"

website:
  body-footer: |
    <br> <br> <span style="color:grey;">&#169; Phil Chodrow, 2023</span>
  sidebar:
    collapse-level: 1	
    style: "docked"
    title: "<span style='color:white'><b>Math Foundations of Computing</b><br>CSCI 0200</span>"
    contents:
      - syllabus.qmd 
      - schedule.qmd
      - section: "Additional Pages"
        contents: 
          - pages/llms.qmd
          - pages/mask-policy.qmd
  favicon: assets/icons/favicon.png
 
format:
  html:
    theme: [cosmo, assets/css/custom.scss] 
    css: assets/css/styles.css
    toc: true
    number-depth: 0
    reference-location: margin
    callout-icon: false;
    callout-appearance: simple

execute: 
  cache: true



